Bump the minor-frontend group in /frontend with 6 updates (#3591)
Bumps the minor-frontend group in /frontend with 6 updates:

| Package | From | To |
| --- | --- | --- |
| [@emotion/react](https://github.com/emotion-js/emotion) | `11.13.0` |
`11.13.3` |
| [axios](https://github.com/axios/axios) | `1.7.4` | `1.7.5` |
| [vite](https://github.com/vitejs/vite/tree/HEAD/packages/vite) |
`5.4.1` | `5.4.2` |
|
[@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node)
| `22.4.1` | `22.5.0` |
|
[@types/react](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/react)
| `18.3.3` | `18.3.4` |
|
[cspell](https://github.com/streetsidesoftware/cspell/tree/HEAD/packages/cspell)
| `8.14.1` | `8.14.2` |

Updates `@emotion/react` from 11.13.0 to 11.13.3
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/emotion-js/emotion/releases"><code>@​emotion/react</code>'s
releases</a>.</em></p>
<blockquote>
<h2><code>@​emotion/react</code><a
href="https://github.com/11"><code>@​11</code></a>.13.3</h2>
<h3>Patch Changes</h3>
<ul>
<li>
<p><a
href="https://redirect.github.com/emotion-js/emotion/pull/3232">#3232</a>
<a
href="https://github.com/emotion-js/emotion/commit/0ce3ed0ff3f7d1ddf91db2859f863f230b063e13"><code>0ce3ed0</code></a>
Thanks <a
href="https://github.com/ENvironmentSet"><code>@​ENvironmentSet</code></a>!
- Distribute <code>css</code> prop attachment over props that are union
types</p>
</li>
<li>
<p>Updated dependencies []:</p>
<ul>
<li><code>@​emotion/serialize</code><a
href="https://github.com/1"><code>@​1</code></a>.3.1</li>
</ul>
</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/emotion-js/emotion/commit/3f468846855ed1c6092922a6317a6f5df0ba8dcc"><code>3f46884</code></a>
Version Packages (<a
href="https://redirect.github.com/emotion-js/emotion/issues/3235">#3235</a>)</li>
<li><a
href="https://github.com/emotion-js/emotion/commit/153cf885521f642462823a25675aa1a5be431db7"><code>153cf88</code></a>
Add scale property as unitless (<a
href="https://redirect.github.com/emotion-js/emotion/issues/3240">#3240</a>)</li>
<li><a
href="https://github.com/emotion-js/emotion/commit/0ce3ed0ff3f7d1ddf91db2859f863f230b063e13"><code>0ce3ed0</code></a>
Distribute <code>css</code> prop attachment over props that are union
types (<a
href="https://redirect.github.com/emotion-js/emotion/issues/3232">#3232</a>)</li>
<li><a
href="https://github.com/emotion-js/emotion/commit/e819f9c39c4485997ce97fd2cfd330be8114e0f8"><code>e819f9c</code></a>
Version Packages (<a
href="https://redirect.github.com/emotion-js/emotion/issues/3229">#3229</a>)</li>
<li><a
href="https://github.com/emotion-js/emotion/commit/49f7435783e2be88ad22012d5156085a25fbcd4e"><code>49f7435</code></a>
Fix broken browser file reference in primitives-core/package.json (<a
href="https://redirect.github.com/emotion-js/emotion/issues/3228">#3228</a>)</li>
<li><a
href="https://github.com/emotion-js/emotion/commit/c6f01a2a5513767f9fd0fe63b019329f56e8e95c"><code>c6f01a2</code></a>
Version Packages (<a
href="https://redirect.github.com/emotion-js/emotion/issues/3224">#3224</a>)</li>
<li><a
href="https://github.com/emotion-js/emotion/commit/c72d2798fe5d9e245ebe91e1b612919fda4ee0cf"><code>c72d279</code></a>
Remove incorrect tripleslash directives referencing node types (<a
href="https://redirect.github.com/emotion-js/emotion/issues/3219">#3219</a>)</li>
<li>See full diff in <a
href="https://github.com/emotion-js/emotion/compare/@emotion/react@11.13.0...@emotion/react@11.13.3">compare
view</a></li>
</ul>
</details>
<br />

Updates `axios` from 1.7.4 to 1.7.5
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/axios/axios/releases">axios's
releases</a>.</em></p>
<blockquote>
<h2>Release v1.7.5</h2>
<h2>Release notes:</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>adapter:</strong> fix undefined reference to hasBrowserEnv
(<a
href="https://redirect.github.com/axios/axios/issues/6572">#6572</a>)
(<a
href="https://github.com/axios/axios/commit/7004707c4180b416341863bd86913fe4fc2f1df1">7004707</a>)</li>
<li><strong>core:</strong> add the missed implementation of
AxiosError#status property; (<a
href="https://redirect.github.com/axios/axios/issues/6573">#6573</a>)
(<a
href="https://github.com/axios/axios/commit/6700a8adac06942205f6a7a21421ecb36c4e0852">6700a8a</a>)</li>
<li><strong>core:</strong> fix <code>ReferenceError: navigator is not
defined</code> for custom environments; (<a
href="https://redirect.github.com/axios/axios/issues/6567">#6567</a>)
(<a
href="https://github.com/axios/axios/commit/fed1a4b2d78ed4a588c84e09d32749ed01dc2794">fed1a4b</a>)</li>
<li><strong>fetch:</strong> fix credentials handling in Cloudflare
workers (<a
href="https://redirect.github.com/axios/axios/issues/6533">#6533</a>)
(<a
href="https://github.com/axios/axios/commit/550d885eb90fd156add7b93bbdc54d30d2f9a98d">550d885</a>)</li>
</ul>
<h3>Contributors to this release</h3>
<ul>
<li><!-- raw HTML omitted --> <a
href="https://github.com/DigitalBrainJS" title="+187/-83
([#6573](https://github.com/axios/axios/issues/6573)
[#6567](https://github.com/axios/axios/issues/6567)
[#6566](https://github.com/axios/axios/issues/6566)
[#6564](https://github.com/axios/axios/issues/6564)
[#6563](https://github.com/axios/axios/issues/6563)
[#6557](https://github.com/axios/axios/issues/6557)
[#6556](https://github.com/axios/axios/issues/6556)
[#6555](https://github.com/axios/axios/issues/6555)
[#6554](https://github.com/axios/axios/issues/6554)
[#6552](https://github.com/axios/axios/issues/6552) )">Dmitriy
Mozgovoy</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/antoninbas"
title="+6/-6 ([#6572](https://github.com/axios/axios/issues/6572)
)">Antonin Bas</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/hansottowirtz"
title="+4/-1 ([#6533](https://github.com/axios/axios/issues/6533)
)">Hans Otto Wirtz</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/axios/axios/blob/v1.x/CHANGELOG.md">axios's
changelog</a>.</em></p>
<blockquote>
<h2><a
href="https://github.com/axios/axios/compare/v1.7.4...v1.7.5">1.7.5</a>
(2024-08-23)</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>adapter:</strong> fix undefined reference to hasBrowserEnv
(<a
href="https://redirect.github.com/axios/axios/issues/6572">#6572</a>)
(<a
href="https://github.com/axios/axios/commit/7004707c4180b416341863bd86913fe4fc2f1df1">7004707</a>)</li>
<li><strong>core:</strong> add the missed implementation of
AxiosError#status property; (<a
href="https://redirect.github.com/axios/axios/issues/6573">#6573</a>)
(<a
href="https://github.com/axios/axios/commit/6700a8adac06942205f6a7a21421ecb36c4e0852">6700a8a</a>)</li>
<li><strong>core:</strong> fix <code>ReferenceError: navigator is not
defined</code> for custom environments; (<a
href="https://redirect.github.com/axios/axios/issues/6567">#6567</a>)
(<a
href="https://github.com/axios/axios/commit/fed1a4b2d78ed4a588c84e09d32749ed01dc2794">fed1a4b</a>)</li>
<li><strong>fetch:</strong> fix credentials handling in Cloudflare
workers (<a
href="https://redirect.github.com/axios/axios/issues/6533">#6533</a>)
(<a
href="https://github.com/axios/axios/commit/550d885eb90fd156add7b93bbdc54d30d2f9a98d">550d885</a>)</li>
</ul>
<h3>Contributors to this release</h3>
<ul>
<li><!-- raw HTML omitted --> <a
href="https://github.com/DigitalBrainJS" title="+187/-83
([#6573](https://github.com/axios/axios/issues/6573)
[#6567](https://github.com/axios/axios/issues/6567)
[#6566](https://github.com/axios/axios/issues/6566)
[#6564](https://github.com/axios/axios/issues/6564)
[#6563](https://github.com/axios/axios/issues/6563)
[#6557](https://github.com/axios/axios/issues/6557)
[#6556](https://github.com/axios/axios/issues/6556)
[#6555](https://github.com/axios/axios/issues/6555)
[#6554](https://github.com/axios/axios/issues/6554)
[#6552](https://github.com/axios/axios/issues/6552) )">Dmitriy
Mozgovoy</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/antoninbas"
title="+6/-6 ([#6572](https://github.com/axios/axios/issues/6572)
)">Antonin Bas</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/hansottowirtz"
title="+4/-1 ([#6533](https://github.com/axios/axios/issues/6533)
)">Hans Otto Wirtz</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/axios/axios/commit/59cd6b0dece4050b190717a7c5cdf77906ce2104"><code>59cd6b0</code></a>
chore(release): v1.7.5 (<a
href="https://redirect.github.com/axios/axios/issues/6574">#6574</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/6700a8adac06942205f6a7a21421ecb36c4e0852"><code>6700a8a</code></a>
fix(core): add the missed implementation of AxiosError#status property;
(<a
href="https://redirect.github.com/axios/axios/issues/6573">#6573</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/7004707c4180b416341863bd86913fe4fc2f1df1"><code>7004707</code></a>
fix(adapter): fix undefined reference to hasBrowserEnv (<a
href="https://redirect.github.com/axios/axios/issues/6572">#6572</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/fed1a4b2d78ed4a588c84e09d32749ed01dc2794"><code>fed1a4b</code></a>
fix(core): fix <code>ReferenceError: navigator is not defined</code> for
custom environm...</li>
<li><a
href="https://github.com/axios/axios/commit/550d885eb90fd156add7b93bbdc54d30d2f9a98d"><code>550d885</code></a>
fix(fetch): fix credentials handling in Cloudflare workers (<a
href="https://redirect.github.com/axios/axios/issues/6533">#6533</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/bcd1c6d65ada866b732c1ffabe6940f99b12d702"><code>bcd1c6d</code></a>
chore(actions): fix sponsor action; (<a
href="https://redirect.github.com/axios/axios/issues/6566">#6566</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/c8b7be59cba56e8fd09dc667de246117987d7517"><code>c8b7be5</code></a>
chore(action): exclude <code>sponsors</code> branch from CI tests; (<a
href="https://redirect.github.com/axios/axios/issues/6564">#6564</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/67aa1effe48c0dced70d139ea13e7d6dff734637"><code>67aa1ef</code></a>
chore(sponsor): update sponsor block (<a
href="https://redirect.github.com/axios/axios/issues/6559">#6559</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/ff254a5065f1aeb50a62b9e3f16290d6d501c78d"><code>ff254a5</code></a>
chore(action): change sponsors uri origin; (<a
href="https://redirect.github.com/axios/axios/issues/6563">#6563</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/4f99675fe7eae503422f932b9407242dbc1b7d55"><code>4f99675</code></a>
chore(sponsor): update sponsor block (<a
href="https://redirect.github.com/axios/axios/issues/6558">#6558</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/axios/axios/compare/v1.7.4...v1.7.5">compare
view</a></li>
</ul>
</details>
<br />

Updates `vite` from 5.4.1 to 5.4.2
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md">vite's
changelog</a>.</em></p>
<blockquote>
<h2><!-- raw HTML omitted -->5.4.2 (2024-08-20)<!-- raw HTML omitted
--></h2>
<ul>
<li>chore: remove stale TODOs (<a
href="https://github.com/vitejs/vite/tree/HEAD/packages/vite/issues/17866">#17866</a>)
(<a
href="https://github.com/vitejs/vite/commit/e012f296df583bd133d26399397bd4ae49de1497">e012f29</a>),
closes <a
href="https://redirect.github.com/vitejs/vite/issues/17866">#17866</a></li>
<li>refactor: remove redundant prepend/strip base (<a
href="https://github.com/vitejs/vite/tree/HEAD/packages/vite/issues/17887">#17887</a>)
(<a
href="https://github.com/vitejs/vite/commit/3b8f03d789ec3ef1a099c884759bd4e61b03ce7c">3b8f03d</a>),
closes <a
href="https://redirect.github.com/vitejs/vite/issues/17887">#17887</a></li>
<li>fix: resolve relative URL generated by <code>renderBuiltUrl</code>
passed to module preload (<a
href="https://github.com/vitejs/vite/tree/HEAD/packages/vite/issues/16084">#16084</a>)
(<a
href="https://github.com/vitejs/vite/commit/fac3a8ed6855c4ab3032957137b74f21ec501e72">fac3a8e</a>),
closes <a
href="https://redirect.github.com/vitejs/vite/issues/16084">#16084</a></li>
<li>feat: support originalFilename (<a
href="https://github.com/vitejs/vite/tree/HEAD/packages/vite/issues/17867">#17867</a>)
(<a
href="https://github.com/vitejs/vite/commit/7d8c0e2dcbdea3a3465a1d87e259988e82561035">7d8c0e2</a>),
closes <a
href="https://redirect.github.com/vitejs/vite/issues/17867">#17867</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/vitejs/vite/commit/b1ecdaf6594b48d2fcbff8682e9ef68916806089"><code>b1ecdaf</code></a>
release: v5.4.2</li>
<li><a
href="https://github.com/vitejs/vite/commit/e012f296df583bd133d26399397bd4ae49de1497"><code>e012f29</code></a>
chore: remove stale TODOs (<a
href="https://github.com/vitejs/vite/tree/HEAD/packages/vite/issues/17866">#17866</a>)</li>
<li><a
href="https://github.com/vitejs/vite/commit/3b8f03d789ec3ef1a099c884759bd4e61b03ce7c"><code>3b8f03d</code></a>
refactor: remove redundant prepend/strip base (<a
href="https://github.com/vitejs/vite/tree/HEAD/packages/vite/issues/17887">#17887</a>)</li>
<li><a
href="https://github.com/vitejs/vite/commit/fac3a8ed6855c4ab3032957137b74f21ec501e72"><code>fac3a8e</code></a>
fix: resolve relative URL generated by <code>renderBuiltUrl</code>
passed to module prel...</li>
<li><a
href="https://github.com/vitejs/vite/commit/7d8c0e2dcbdea3a3465a1d87e259988e82561035"><code>7d8c0e2</code></a>
feat: support originalFilename (<a
href="https://github.com/vitejs/vite/tree/HEAD/packages/vite/issues/17867">#17867</a>)</li>
<li>See full diff in <a
href="https://github.com/vitejs/vite/commits/v5.4.2/packages/vite">compare
view</a></li>
</ul>
</details>
<br />

Updates `@types/node` from 22.4.1 to 22.5.0
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/node">compare
view</a></li>
</ul>
</details>
<br />

Updates `@types/react` from 18.3.3 to 18.3.4
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/react">compare
view</a></li>
</ul>
</details>
<br />

Updates `cspell` from 8.14.1 to 8.14.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/streetsidesoftware/cspell/releases">cspell's
releases</a>.</em></p>
<blockquote>
<h2>v8.14.2</h2>
<h2>Changes</h2>
<h2>Fixes</h2>
<!-- raw HTML omitted -->
<h3>fix: Remove timeout in ESLint plugin (<a
href="https://github.com/streetsidesoftware/cspell/tree/HEAD/packages/cspell/issues/6124">#6124</a>)</h3>
<p>fixes <a
href="https://github.com/streetsidesoftware/cspell/tree/HEAD/packages/cspell/issues/5825">#5825</a></p>
<hr />
<!-- raw HTML omitted -->
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/streetsidesoftware/cspell/blob/main/packages/cspell/CHANGELOG.md">cspell's
changelog</a>.</em></p>
<blockquote>
<h2><!-- raw HTML omitted -->8.14.2 (2024-08-20)<!-- raw HTML omitted
--></h2>
<ul>
<li>chore: Update Integration Test Performance Data (<a
href="https://github.com/streetsidesoftware/cspell/tree/HEAD/packages/cspell/issues/6126">#6126</a>)
(<a
href="https://github.com/streetsidesoftware/cspell/commit/012c897">012c897</a>),
closes <a
href="https://redirect.github.com/streetsidesoftware/cspell/issues/6126">#6126</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/streetsidesoftware/cspell/commit/9f7c1831d4765d35f289b2a623133fc21bee4dcd"><code>9f7c183</code></a>
v8.14.2</li>
<li>See full diff in <a
href="https://github.com/streetsidesoftware/cspell/commits/v8.14.2/packages/cspell">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Ben Hammond <benjamin.hammond@gmail.com>